app: tally-client
name: tally-client
component: website
org: aroger7

useDotenv: true

provider:
  name: aws
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: '*'

inputs:
  bucketName: tally-react-client
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
