plugins:
  - serverless-offline

custom:
  serverless-offline:
    noTimeout: true


service: get-batch-counts-service
app: tally-backend
org: aroger7

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  getBatchCounts:
    handler: index.handler
    name: ${self:provider.stage}-get-batch-counts-function
    timeout: 120
