plugins:
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 3003

service: mock-steam-api
app: tally-backend
org: aroger7

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  mockSteamApi:
    handler: index.handler
    events:
      - http:
          path: /{path}
          method: GET
          cors: true
          private: false
    name: ${self:provider.stage}-mock-steam-api
