name: deploy-client
on:
  push:
    branches:
      - 'ci/cd'
    paths:
      - 'client/**'
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm test