name: Deploy client
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: client
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - name: Serverless
        uses: serverless/github-action@v2.17.1
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy -s ${GITHUB_REF#refs/heads/}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
