name: deploy-client
on:
  push:
    branches:
      - 'ci/cd'
    paths:
      - 'client/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: client
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Serverless
        uses: serverless/github-action@v.1.53.0
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
