name: Deploy count update service
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'services/count-update-service/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: services/count-update-service
jobs:
  deploy:
    name: Deploy stats API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: env
      - run: npm ci
      # - run: npm test
      # - run: npm run build --if-present
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage ${{ steps.env.outputs.branch }}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
