name: Deploy client
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: client
env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: nelonoel/branch-name@v1.0.1
      - run: npm ci
      - run: npx serverless deploy --stage ${{ env.BRANCH_NAME }}
