name: Deploy client
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: client
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: vars
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage ${GITHUB_REF#refs/heads/}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
