name: deploy-client
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'layers/**'
  workflow_dispatch:
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: layers/nodejs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: layers
    steps:
      - name: Serverless
        uses: serverless/github-action@v2.17.1
      - uses: actions/checkout@v2
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy -s ${GITHUB_REF#refs/heads/}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
