name: Deploy stats API
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'services/stats-api/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: services/stats-api
env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
jobs:
  deploy:
    name: Deploy stats API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: nelonoel/branch-name@v1.0.1
      # - name: Get branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: env
      - run: npm ci
      - run: npm ci
        working-directory: ./
      # - run: npm install serverless
      # - run: serverless deploy --stage $BRANCH_NAME
      - run: npx serverless deploy --stage ${{ env.BRANCH_NAME }}
      # - run: npm test
      # - run: npm run build --if-present
      # - name: serverless deploy
      #   uses: serverless/github-action@master
      #   with:
      #     args: deploy --stage $BRANCH_NAME
      #   env:
      #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
