name: deploy-client
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'client/**'
  workflow_dispatch:
defaults:
  run:
    working-directory: client
jobs:
  deploy-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      # - name: Extract branch name
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      - name: Serverless
        uses: serverless/github-action@v2.17.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test
      - run: echo ${{ github.head_ref }}
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy -s dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
